---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/component: app
spec:
  ports:
  - port: 9000
    name: app-port
    targetPort: app-port
    protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/component: app
